dist: trusty

language: python

# Runs jobs on container based infrastructure
sudo: false

# Saves pip downloads/wheels between builds
cache:
  directories:
    - $HOME/.cache/pip

addons:
    apt:
        packages:
            - libhidapi-dev
            - libudev-dev
            - libusb-1.0-0-dev

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    # Optimisation: build requirements as wheels, which get cached by Travis
    - pip install "pip>=8.0" "wheel" "setuptools>=19.0"
    - pip install tox-travis
    - pip install -r requirements.txt

env:
    - EXTRAOPTION=
    - EXTRAOPTION=--without-libusb
    - EXTRAOPTION=--with-system-hidapi
    - EXTRAOPTION=--with-system-hidapi --without-libusb

script:
    - python setup.py install $EXTRAOPTION
    - tox

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
